CREATE TABLE EMPLOYEE(
    Emp_no INT PRIMARY KEY,
    E_name VARCHAR(50),
    E_address VARCHAR(100),
    E_ph_no INT,
    Dept_no INT,
    Dept_name VARCHAR(50),
    Job_id INT,
    Salary FLOAT
);

ALTER TABLE EMPLOYEE
ADD HIREDATE DATE;

//RENAME TABLE EMPLOYEE TO EMP;
RENAME EMP TO STAFF;
ALTER TABLE STAFF RENAME TO EMP;

ALTER TABLE EMP
MODIFY JOB_ID VARCHAR(15);

ALTER TABLE EMP
RENAME COLUMN EMP_NO TO E_no;

ALTER TABLE EMP
MODIFY JOB_ID VARCHAR(10);

desc EMP;
SELECT * FROM EMP;